## 2. Creating tensors with NumPy (Creating vectors and matrices)

In [1]:
import numpy as np

### 1) 1D with Numpy

In [2]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
# In plain Python: create a list and convert it to a 1D array with np.array.
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [3]:
print('Rank of t: ', t.ndim)
print('Shape of t: ', t.shape)

Rank of t:  1
Shape of t:  (7,)


#### 1-1) Understanding NumPy basics

In [5]:
print('t[0] t[1] t[-1] = ', t[0], t[1], t[-1]) # Access elements via indexing

t[0] t[1] t[-1] =  0.0 1.0 6.0


In [6]:
print('t[2:5] t[4:-1]  = ', t[2:5], t[4:-1]) # Use [start_index : end_index] slicing to specify a range.

t[2:5] t[4:-1]  =  [2. 3. 4.] [4. 5.]


In [7]:
print('t[:2] t[3:]     = ', t[:2], t[3:]) # Cases where the start index is omitted and where the end index is omitted

t[:2] t[3:]     =  [0. 1.] [3. 4. 5. 6.]


## 3. Creating PyTorch tensors (PyTorch Tensor Allocation)

In [8]:
import torch

### 1) 1D with PyTorch

In [9]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [10]:
print(t.dim())  # Rank, i.e., the number of dimensions
print(t.shape)  # shape
print(t.size()) # shape

1
torch.Size([7])
torch.Size([7])


In [11]:
print(t[0], t[1], t[-1])  # Access by index
print(t[2:5], t[4:-1])    # Slicing
print(t[:2], t[3:])       # Slicing

tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


### 2) 2D with PyTorch

In [12]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [13]:
print(t.dim())  # Rank, i.e., the number of dimensions
print(t.size()) # shape

2
torch.Size([4, 3])


In [14]:
print(t[:, 1]) # With all of the first dimension selected, take only the first element of the second dimension.
print(t[:, 1].size()) # ↑ Size in the above case

tensor([ 2.,  5.,  8., 11.])
torch.Size([4])


In [15]:
print(t[:, :-1]) # With all of the first dimension selected, take everything in the second dimension except the last element.

tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


### 3) Broadcasting

In [16]:
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)

tensor([[5., 5.]])


In [17]:
# Vector + scalar
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3]) # [3] -> [3, 3]
print(m1 + m2)

tensor([[4., 5.]])


In [18]:
# 2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


## 4. Frequently used operations

### 1) Matrix multiplication vs. element-wise multiplication (Matrix Multiplication Vs. Multiplication)

In [19]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1.matmul(m2)) # 2 x 1

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


In [20]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1 * m2) # 2 x 2
print(m1.mul(m2))

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


### 2) Mean

In [21]:
t = torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


In [22]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [23]:
print(t.mean())

tensor(2.5000)


In [24]:
print(t.mean(dim=0))

tensor([2., 3.])


In [25]:
print(t.mean(dim=1))

tensor([1.5000, 3.5000])


In [26]:
print(t.mean(dim=-1))

tensor([1.5000, 3.5000])


### 3) Sum

In [27]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [28]:
print(t.sum()) # Simply sum all elements
print(t.sum(dim=0)) # Remove a row
print(t.sum(dim=1)) # Remove a column
print(t.sum(dim=-1)) # Remove a column

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


### 4) Max and ArgMax

In [29]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [30]:
print(t.max()) # Returns one value: max

tensor(4.)


In [31]:
print(t.max(dim=0)) # Returns two values: max and argmax

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))


In [32]:
print('Max: ', t.max(dim=0)[0])
print('Argmax: ', t.max(dim=0)[1])

Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])


In [33]:
print(t.max(dim=1))
print(t.max(dim=-1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


### 5) View - Change tensor shape while keeping the number of elements. Very important!


In [34]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)

In [35]:
print(ft.shape)

torch.Size([2, 2, 3])


In [36]:
print(ft.view([-1, 3])) # Reshape tensor ft to size (?, 3)
print(ft.view([-1, 3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [37]:
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


### 6) Squeeze - Remove dimensions of size 1.

In [38]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [39]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


### 7) Unsqueeze - Add a dimension of size 1 at a specific position.

In [40]:
ft = torch.Tensor([0, 1, 2])
print(ft.shape)

torch.Size([3])


In [41]:
print(ft.unsqueeze(0)) # Since indexing starts at 0, 0 refers to the first dimension.
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [42]:
print(ft.view(1, -1))
print(ft.view(1, -1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [43]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [44]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


### 8) Type casting (Type Casting)

In [45]:
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)

tensor([1, 2, 3, 4])


In [46]:
print(lt.float())

tensor([1., 2., 3., 4.])


In [47]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [48]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


### 9) Concatenate

In [49]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

In [50]:
print(torch.cat([x, y], dim=0))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


In [51]:
print(torch.cat([x, y], dim=1))

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


### 10) Stacking

In [52]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

In [53]:
print(torch.stack([x, y, z]))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [54]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [55]:
print(torch.stack([x, y, z], dim=1))

tensor([[1., 2., 3.],
        [4., 5., 6.]])


### 11) ones_like and zeros_like - tensors filled with 0s and 1s


In [56]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [57]:
print(torch.ones_like(x)) # Create a tensor of the same size filled with ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [58]:
print(torch.zeros_like(x)) # Create a tensor of the same size filled with zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])


### 12) In-place operation (Overwrite operation)

In [59]:
x = torch.FloatTensor([[1, 2], [3, 4]])

In [60]:
print(x.mul(2.)) # Print the result of multiplying by 2
print(x) # Print the original value

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])


In [61]:
print(x.mul_(2.))  # Multiply by 2, store the result in x, and print it
print(x) # Print the original value

tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
