## 1. Implement simple linear regression

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [ ]:
torch.manual_seed(1)

In [ ]:
# Data
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [ ]:
# Declare and initialize the model: simple linear regression (input_dim=1, output_dim=1).
model = nn.Linear(1,1)

In [ ]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [ ]:
# Set up the optimizer: use SGD for gradient descent; lr (learning rate) = 0.01
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

In [ ]:
# Repeat gradient descent 2,000 times over the full training set
nb_epochs = 2000
for epoch in range(nb_epochs+1):

    # Compute H(x)
    prediction = model(x_train)

    # Compute cost
    cost = F.mse_loss(prediction, y_train) # <== Mean squared error function provided by PyTorch

    # The part that updates H(x) using the cost
    # Initialize gradients to zero
    optimizer.zero_grad()
    # Compute gradients by differentiating the cost function
    cost.backward() # Backward pass
    # Update W and b
    optimizer.step()

    if epoch % 100 == 0:
    # Print logs every 100 steps
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 13.103541
Epoch  100/2000 Cost: 0.002791
Epoch  200/2000 Cost: 0.001724
Epoch  300/2000 Cost: 0.001066
Epoch  400/2000 Cost: 0.000658
Epoch  500/2000 Cost: 0.000407
Epoch  600/2000 Cost: 0.000251
Epoch  700/2000 Cost: 0.000155
Epoch  800/2000 Cost: 0.000096
Epoch  900/2000 Cost: 0.000059
Epoch 1000/2000 Cost: 0.000037
Epoch 1100/2000 Cost: 0.000023
Epoch 1200/2000 Cost: 0.000014
Epoch 1300/2000 Cost: 0.000009
Epoch 1400/2000 Cost: 0.000005
Epoch 1500/2000 Cost: 0.000003
Epoch 1600/2000 Cost: 0.000002
Epoch 1700/2000 Cost: 0.000001
Epoch 1800/2000 Cost: 0.000001
Epoch 1900/2000 Cost: 0.000000
Epoch 2000/2000 Cost: 0.000000


In [ ]:
# Define an arbitrary input 4
new_var = torch.FloatTensor([[4.0]])
# Get the prediction y for input 4 and store it in pred_y
pred_y = model(new_var) # Forward pass
# Since y = 2x, if the input is 4, y should be close to 8 when training is done correctly
print("Predicted value for input 4 after training:", pred_y)

훈련 후 입력이 4일 때의 예측값 : tensor([[7.9989]], grad_fn=<AddmmBackward0>)


In [ ]:
print(list(model.parameters()))

[Parameter containing:
tensor([[1.9994]], requires_grad=True), Parameter containing:
tensor([0.0014], requires_grad=True)]


## 2. Implement multivariable linear regression

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [ ]:
torch.manual_seed(1)

In [ ]:
# Data
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [ ]:
# Declare and initialize the model: multivariable linear regression (input_dim=3, output_dim=1).
model = nn.Linear(3,1)

In [ ]:
print(list(model.parameters()))

[Parameter containing:
tensor([[ 0.2975, -0.2548, -0.1119]], requires_grad=True), Parameter containing:
tensor([0.2710], requires_grad=True)]


In [ ]:
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

In [ ]:
nb_epochs = 2000
for epoch in range(nb_epochs+1):

    # Compute H(x)
    prediction = model(x_train)
    # model(x_train) is the same as model.forward(x_train).

    # Compute cost
    cost = F.mse_loss(prediction, y_train) # <== Mean squared error function provided by PyTorch

    # The part that updates H(x) using the cost
    # Initialize gradients to zero
    optimizer.zero_grad()
    # Compute gradients by differentiating the cost function
    cost.backward()
    # Update W and b
    optimizer.step()

    if epoch % 100 == 0:
    # Print logs every 100 steps
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 31667.597656
Epoch  100/2000 Cost: 0.225993
Epoch  200/2000 Cost: 0.223911
Epoch  300/2000 Cost: 0.221941
Epoch  400/2000 Cost: 0.220059
Epoch  500/2000 Cost: 0.218271
Epoch  600/2000 Cost: 0.216575
Epoch  700/2000 Cost: 0.214950
Epoch  800/2000 Cost: 0.213413
Epoch  900/2000 Cost: 0.211952
Epoch 1000/2000 Cost: 0.210560
Epoch 1100/2000 Cost: 0.209232
Epoch 1200/2000 Cost: 0.207967
Epoch 1300/2000 Cost: 0.206761
Epoch 1400/2000 Cost: 0.205619
Epoch 1500/2000 Cost: 0.204522
Epoch 1600/2000 Cost: 0.203484
Epoch 1700/2000 Cost: 0.202485
Epoch 1800/2000 Cost: 0.201542
Epoch 1900/2000 Cost: 0.200635
Epoch 2000/2000 Cost: 0.199769


In [ ]:
# Define an arbitrary input [73, 80, 75]
new_var =  torch.FloatTensor([[73, 80, 75]])
# Get the prediction y for input [73, 80, 75] and store it in pred_y
pred_y = model(new_var)
print("Predicted values for inputs 73, 80, 75 after training:", pred_y)

훈련 후 입력이 73, 80, 75일 때의 예측값 : tensor([[151.2305]], grad_fn=<AddmmBackward0>)


In [ ]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.9778, 0.4539, 0.5768]], requires_grad=True), Parameter containing:
tensor([0.2802], requires_grad=True)]


## 3. Implement the model as a class

In [ ]:
class LinearRegressionModel(nn.Module): # A Python class that inherits from torch.nn.Module
    def __init__(self): #
        super().__init__()
        self.linear = nn.Linear(1, 1) # For simple linear regression: input_dim=1, output_dim=1.

    def forward(self, x):
        return self.linear(x)

In [ ]:
model = LinearRegressionModel()

In [ ]:
# Declare and initialize the model: multivariable linear regression (input_dim=3, output_dim=1).
model = nn.Linear(3,1)

In [ ]:
class MultivariateLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3, 1) # For multivariate linear regression: input_dim=3, output_dim=1.

    def forward(self, x):
        return self.linear(x)

In [ ]:
model = MultivariateLinearRegressionModel()

## 4. Implement simple linear regression as a class

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [ ]:
torch.manual_seed(1)

In [ ]:
# Data
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [ ]:
class LinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(1, 1)

    def forward(self, x):
        return self.linear(x)

In [ ]:
model = LinearRegressionModel()

In [ ]:
# Set up the optimizer: use SGD for gradient descent; lr (learning rate) = 0.01
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

In [ ]:
# Repeat gradient descent 2,000 times over the full training set
nb_epochs = 2000
for epoch in range(nb_epochs+1):

    # Compute H(x)
    prediction = model(x_train)

    # Compute cost
    cost = F.mse_loss(prediction, y_train) # <== Mean squared error function provided by PyTorch

    # The part that updates H(x) using the cost
    # Initialize gradients to zero
    optimizer.zero_grad()
    # Compute gradients by differentiating the cost function
    cost.backward() # Backward pass
    # Update W and b
    optimizer.step()

    if epoch % 100 == 0:
    # Print logs every 100 steps
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 13.103541
Epoch  100/2000 Cost: 0.002791
Epoch  200/2000 Cost: 0.001724
Epoch  300/2000 Cost: 0.001066
Epoch  400/2000 Cost: 0.000658
Epoch  500/2000 Cost: 0.000407
Epoch  600/2000 Cost: 0.000251
Epoch  700/2000 Cost: 0.000155
Epoch  800/2000 Cost: 0.000096
Epoch  900/2000 Cost: 0.000059
Epoch 1000/2000 Cost: 0.000037
Epoch 1100/2000 Cost: 0.000023
Epoch 1200/2000 Cost: 0.000014
Epoch 1300/2000 Cost: 0.000009
Epoch 1400/2000 Cost: 0.000005
Epoch 1500/2000 Cost: 0.000003
Epoch 1600/2000 Cost: 0.000002
Epoch 1700/2000 Cost: 0.000001
Epoch 1800/2000 Cost: 0.000001
Epoch 1900/2000 Cost: 0.000000
Epoch 2000/2000 Cost: 0.000000


## 5. Implement multivariable linear regression as a class

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [ ]:
torch.manual_seed(1)

In [ ]:
# Data
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [ ]:
class MultivariateLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3, 1) # For multivariate linear regression: input_dim=3, output_dim=1.

    def forward(self, x):
        return self.linear(x)

model = MultivariateLinearRegressionModel()

In [ ]:
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

In [ ]:
nb_epochs = 2000
for epoch in range(nb_epochs+1):

    # Compute H(x)
    prediction = model(x_train)
    # model(x_train) is the same as model.forward(x_train).

    # Compute cost
    cost = F.mse_loss(prediction, y_train) # <== Mean squared error function provided by PyTorch

    # The part that updates H(x) using the cost
    # Initialize gradients to zero
    optimizer.zero_grad()
    # Compute gradients by differentiating the cost function
    cost.backward()
    # Update W and b
    optimizer.step()

    if epoch % 100 == 0:
    # Print logs every 100 steps
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 31667.597656
Epoch  100/2000 Cost: 0.225993
Epoch  200/2000 Cost: 0.223911
Epoch  300/2000 Cost: 0.221941
Epoch  400/2000 Cost: 0.220059
Epoch  500/2000 Cost: 0.218271
Epoch  600/2000 Cost: 0.216575
Epoch  700/2000 Cost: 0.214950
Epoch  800/2000 Cost: 0.213413
Epoch  900/2000 Cost: 0.211952
Epoch 1000/2000 Cost: 0.210560
Epoch 1100/2000 Cost: 0.209232
Epoch 1200/2000 Cost: 0.207967
Epoch 1300/2000 Cost: 0.206761
Epoch 1400/2000 Cost: 0.205619
Epoch 1500/2000 Cost: 0.204522
Epoch 1600/2000 Cost: 0.203484
Epoch 1700/2000 Cost: 0.202485
Epoch 1800/2000 Cost: 0.201542
Epoch 1900/2000 Cost: 0.200635
Epoch 2000/2000 Cost: 0.199769
